language: node_js
addons:
  firefox: latest
node_js:
 - "14"
 - "12"
 - "10"
script: npm test

jobs:
  include:
    - name: Coverage
      os: linux
      node_js: "14"
      script: npm run coveralls
