name: CI
on:
  - push
  - pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  tests:
    strategy:
      matrix:
        node:
          - 10.x
          - 12.x
          - 14.x
          - 16.x
          - 18.x

    # Packages 'firefox' and 'chromium' are pre-installed.
    #
    # https://github.com/actions/runner-images/blob/ubuntu22/20230402.1/images/linux/Ubuntu2204-Readme.md
    runs-on: ubuntu-22.04
    name: Node.js ${{ matrix.node }}
    steps:
      # Clone the repo and checkout the commit for which the workflow was triggered

      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        if: ${{ runner.os != 'Windows' }}
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: npm ci

      - name: Tests
        run: npm test
