name: Coverage
on:
  - push

jobs:

  coveralls:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install
        run: npm install

      - name: Tests
        run: npm run cover

      - name: Upload
        env:
          COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
          COVERALLS_GIT_BRANCH: "${{ github.ref }}"
        run: |
          wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.5.3/php-coveralls.phar
          chmod +x php-coveralls.phar
          ./php-coveralls.phar -v --coverage_clover coverage/clover.xml --json_path coverage/coveralls.json
